# Generated by Django 2.1.3 on 2018-11-14 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('service_id', models.PositiveIntegerField(verbose_name='Идентификатор задачи')),
                ('title', models.CharField(max_length=255, verbose_name='Имя задачи')),
                ('primary_color', models.CharField(max_length=7, verbose_name='Главный цвет')),
                ('url', models.CharField(max_length=255, verbose_name='Адрес загрузки')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Признак выполнения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
