# Generated by Django 2.1.3 on 2018-11-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='about_us',
            field=models.CharField(default='ddfs', max_length=255, verbose_name='О ресторане'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='facebook',
            field=models.CharField(default='asd', max_length=255, verbose_name='Ссылка в Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='instagram',
            field=models.CharField(default='das', max_length=255, verbose_name='Ссылка в Instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='site',
            field=models.CharField(default='asd', max_length=255, verbose_name='Ссылка на сайт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='vk',
            field=models.CharField(default='dsadwq', max_length=255, verbose_name='Ссылка в VK'),
            preserve_default=False,
        ),
    ]
