# Generated by Django 2.1.3 on 2018-11-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabel', '0003_task_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='about_us_photo',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_photos'),
        ),
    ]
